orchestrate_workflow:
  description: >
    As the primary orchestrator, you will:
    1. Receive and analyze the user's request ({Action})
    2. Create a step-by-step plan to fulfill the request
    3. Determine which agents need to be involved and in what sequence
    4. Coordinate the execution of tasks between agents
    5. Ensure all steps are completed successfully
    6. Provide a summary of actions taken and results achieved

    You have access to these specialized agents:
    - email_processor: For email analysis and communication
    - calendar_manager: For scheduling and calendar management
    - document_manager: For document creation and management
    - spreadsheet_manager: For data tracking and spreadsheet updates

    Based on the user's request, create and execute an appropriate workflow using
    these agents. Ensure each agent is used for its specialized purpose and that
    the workflow is efficient and logical.
  expected_output: >
    A detailed execution report including:
    1. The interpreted user request
    2. The workflow plan created
    3. The agents involved and their roles
    4. The sequence of operations performed
    5. The final outcome and any follow-up actions needed
  agent: supervisor_agent

process_email:
  description: >
    Process and analyze email content. 
    Look for any meeting details such as date, time, participants, 
    or relevant links. Summarize the main points of the conversation 
    and any key decisions or follow-up actions.
  expected_output: >
    A concise summary outlining the extracted meeting details, 
    including date/time, participants, and any identified tasks 
    or decisions that need to be tracked.
  agent: email_processor
  
schedule_meeting:
  description: >
    Schedule a calendar event based on extracted meeting details such
    as date, time, participants, and location. Ensure there are no
    conflicts with existing events and send out invitations or
    notifications to all relevant attendees.
  expected_output: >
    A confirmation of the created calendar event containing the
    date, time, location, and list of participants, along with
    any relevant attachments or links.
  agent: calendar_manager

generate_document:
  description: >
    Generate a meeting document using the designated template, incorporating
    key information such as date, time, participants, and the main
    agenda points or discussion topics.
  expected_output: >
    The unique document ID and a link to the created document,
    ensuring it is accessible to all relevant stakeholders.
  agent: document_manager

update_spreadsheet:
  description: >
    Log all pertinent meeting details in the assigned spreadsheet. This
    includes the date, time, participants, decisions made, and any tasks
    or action items identified during the meeting.
  expected_output: >
    A confirmation that the spreadsheet was successfully updated, along
    with a reference to any newly added or modified rows and cells.
  agent: spreadsheet_manager
